#!/bin/bash

set -e

echo "Cleaning Clipboard Guardian leftovers..."


rm -rf /usr/share/clipboard-guardian || true

rm -f /usr/bin/clipboard-guardian || true

rm -f /usr/lib/systemd/user/clipboard-guardian.service || true


rm -f /tmp/clipboard_guardian*.sock || true

rm -f /tmp/clipboard_guardian_tray.lock || true


systemctl --user daemon-reload \
>/dev/null 2>&1 || true


update-desktop-database \
>/dev/null 2>&1 || true


gtk-update-icon-cache \
/usr/share/icons/hicolor \
>/dev/null 2>&1 || true


exit 0
