#!/bin/bash

set -e

echo "Stopping Clipboard Guardian..."


systemctl --user stop clipboard-guardian.service \
>/dev/null 2>&1 || true


systemctl --user disable clipboard-guardian.service \
>/dev/null 2>&1 || true


systemctl --user daemon-reload \
>/dev/null 2>&1 || true


exit 0
